stages:
  - build
  - test
  - release

build:
  stage: build
  image: $DOCKER_CACHE_REGISTRY/docker:23
  rules:
    - if: "$CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
    - if: $CI_COMMIT_TAG
  services:
    - $DOCKER_CACHE_REGISTRY/docker:23-dind
  variables:
    BUILD_DOCKERFILE: ./Dockerfile
    BUILD_WORKDIR: "."
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -f $BUILD_DOCKERFILE -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG $BUILD_WORKDIR
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

test:
  needs:
    - build
  stage: test
  image: docker:23
  services:
    - docker:23-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker run --rm $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG busted -pattern=_test /usr/local/openresty/nginx/lua

release:
  stage: release
  image: $DOCKER_CACHE_REGISTRY/docker:23
  rules:
    - if: $CI_COMMIT_TAG
  services:
    - $DOCKER_CACHE_REGISTRY/docker:23-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG