build:
  stage: build
  image: $DOCKER_CACHE_REGISTRY/docker:23
  rules:
    - if: $CI_COMMIT_TAG
  services:
    - $DOCKER_CACHE_REGISTRY/docker:23-dind
  variables:
    BUILD_DOCKERFILE: ./Dockerfile
    BUILD_WORKDIR: "."
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - IMAGES_BUILT="$CI_REGISTRY_IMAGE"
    - DOCKER_BUILD_CMD="docker build -f $BUILD_DOCKERFILE -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG $BUILD_WORKDIR"
    - eval "$DOCKER_BUILD_CMD"
    - docker push $CI_REGISTRY_IMAGE --all-tags