services:
  proxy:
    environment:
      - UPSTREAM_HOST=127.0.0.1
      - UPSTREAM_PORT=9000
      - DISTRIBUTED_CACHE_HOST=redis
      - DISTRIBUTED_CACHE_PORT=6379
      - DISTRIBUTED_CACHE_PROVIDER=redis
    build:
      context: .
      target: docker
    ports:
      - "8080:80"
    volumes:
      - ${PWD}/ratelimits.yaml:/usr/local/openresty/nginx/lua/ratelimits.yaml
      - ${PWD}/lua:/usr/local/openresty/nginx/lua
      - ${PWD}/nginx/nginx.docker.conf:/usr/local/openresty/nginx/conf/nginx.conf
    depends_on:
      - redis
      - mcrouter

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"

  mcrouter:
    image: quay.io/evryfs/docker-mcrouter
    command: >
      mcrouter -p 5000 --config-str='{"pools":{"A":{"servers":["memcached:11211"]}},"route":"PoolRoute|A"}'
    ports:
      - "5001:5000"
    depends_on:
      - memcached

  tests:
    build:
      context: .
      target: test
    volumes:
      - ${PWD}/lua:/usr/local/openresty/nginx/lua
    command: busted --pattern=_test /usr/local/openresty/nginx/lua